from typing import Protocol


class AssistantBrain(Protocol):
    @property
    def is_ready(self) -> bool: ...

    @property
    def shutdown_requested(self) -> bool: ...

    def initialize(self) -> None: ...

    def shutdown(self) -> None: ...

    def reply(self, user_text: str) -> str: ...
