from typing import Protocol


class AvatarOverlay(Protocol):
    def initialize(self) -> None: ...

    def run(self) -> None: ...

    def wait_until_ready(self, timeout: float = ...) -> bool: ...

    def shutdown(self) -> None: ...

    def show(self) -> None: ...

    def hide(self) -> None: ...

    def set_level(self, level: float) -> None: ...
