from enum import StrEnum
from typing import Final


class GigaChatScope(StrEnum):
    PERS = "GIGACHAT_API_PERS"
    B2B = "GIGACHAT_API_B2B"
    CORP = "GIGACHAT_API_CORP"


GIGACHAT_DEFAULT_SCOPE: Final[GigaChatScope] = GigaChatScope.PERS
GIGACHAT_DEFAULT_MODEL: Final[str] = "GigaChat"
GIGACHAT_DEFAULT_VERIFY_SSL: Final[bool] = False
GIGACHAT_DEFAULT_TIMEOUT_SECONDS: Final[float] = 30.0
GIGACHAT_DEFAULT_TEMPERATURE: Final[float] = 0.3
GIGACHAT_DEFAULT_MAX_TOKENS: Final[int] = 256
GIGACHAT_MAX_TOOL_ROUNDS: Final[int] = 3

__all__ = (
    "GIGACHAT_DEFAULT_MAX_TOKENS",
    "GIGACHAT_DEFAULT_MODEL",
    "GIGACHAT_DEFAULT_SCOPE",
    "GIGACHAT_DEFAULT_TEMPERATURE",
    "GIGACHAT_DEFAULT_TIMEOUT_SECONDS",
    "GIGACHAT_DEFAULT_VERIFY_SSL",
    "GIGACHAT_MAX_TOOL_ROUNDS",
    "GigaChatScope",
)
