from typing import Final

SPEECH_DEFAULT_RMS: Final[float] = 0.008
SPEECH_DEFAULT_ONSET_SECONDS: Final[float] = 0.15
SPEECH_DEFAULT_MIN_SECONDS: Final[float] = 0.5
SPEECH_DEFAULT_SILENCE_SECONDS: Final[float] = 1.2
SPEECH_DEFAULT_MAX_SECONDS: Final[float] = 12.0
SPEECH_TRIM_WINDOW_SECONDS: Final[float] = 0.02
SPEECH_TRIM_PAD_SECONDS: Final[float] = 0.25
SPEECH_TRIM_THRESHOLD_FACTOR: Final[float] = 0.7
SPEECH_POST_WAKE_READ_TIMEOUT_SECONDS: Final[float] = 0.05

__all__ = (
    "SPEECH_DEFAULT_MAX_SECONDS",
    "SPEECH_DEFAULT_MIN_SECONDS",
    "SPEECH_DEFAULT_ONSET_SECONDS",
    "SPEECH_DEFAULT_RMS",
    "SPEECH_DEFAULT_SILENCE_SECONDS",
    "SPEECH_POST_WAKE_READ_TIMEOUT_SECONDS",
    "SPEECH_TRIM_PAD_SECONDS",
    "SPEECH_TRIM_THRESHOLD_FACTOR",
    "SPEECH_TRIM_WINDOW_SECONDS",
)
