from typing import Final

WAKE_DEFAULT_KEYWORD: Final[str] = "мина"
WAKE_DEFAULT_WINDOW_SECONDS: Final[float] = 2.0
WAKE_DEFAULT_HOP_SECONDS: Final[float] = 1.5
WAKE_DEFAULT_LISTEN_RMS: Final[float] = 0.012
WAKE_DEFAULT_LISTEN_PEAK: Final[float] = 0.03
WAKE_DEFAULT_LISTEN_SNR: Final[float] = 3.0
WAKE_DEFAULT_POST_PRUNE_SECONDS: Final[float] = 0.35
WAKE_DEFAULT_BEAM_SIZE: Final[int] = 2
WAKE_DEFAULT_VAD_FILTER: Final[bool] = True
WAKE_DEFAULT_NO_SPEECH: Final[float] = 0.7
WAKE_MATCH_RATIO: Final[float] = 0.72
WAKE_NOISE_RMS_INITIAL: Final[float] = 0.005
WAKE_NOISE_QUIET_FACTOR: Final[float] = 1.8
WAKE_NOISE_EMA_ALPHA: Final[float] = 0.05
WAKE_NOISE_EMA_BASE: Final[float] = 0.95
WAKE_NOISE_FLOOR_MIN: Final[float] = 1e-6
WAKE_KEYWORD_MIN_CHARS: Final[int] = 3

__all__ = (
    "WAKE_DEFAULT_BEAM_SIZE",
    "WAKE_DEFAULT_HOP_SECONDS",
    "WAKE_DEFAULT_KEYWORD",
    "WAKE_DEFAULT_LISTEN_PEAK",
    "WAKE_DEFAULT_LISTEN_RMS",
    "WAKE_DEFAULT_LISTEN_SNR",
    "WAKE_DEFAULT_NO_SPEECH",
    "WAKE_DEFAULT_POST_PRUNE_SECONDS",
    "WAKE_DEFAULT_VAD_FILTER",
    "WAKE_DEFAULT_WINDOW_SECONDS",
    "WAKE_KEYWORD_MIN_CHARS",
    "WAKE_MATCH_RATIO",
    "WAKE_NOISE_EMA_ALPHA",
    "WAKE_NOISE_EMA_BASE",
    "WAKE_NOISE_FLOOR_MIN",
    "WAKE_NOISE_QUIET_FACTOR",
    "WAKE_NOISE_RMS_INITIAL",
)
